# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-18 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20190918_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
