# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
