# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-11 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20190924_1546'),
        ('match', '0006_auto_20190924_1549'),
    ]

    operations = [
    ]
