# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-11 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_merge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='MatchPerformance',
        ),
        migrations.AlterUniqueTogether(
            name='matchperformance',
            unique_together=set([('match_id', 'summoner')]),
        ),
    ]
