MATCH_QUEUE_TYPE = {
    "72": "Howling Abyss - 1v1 Snowdown Showdown",
    "73": "Howling Abyss - 2v2 Snowdown Showdown",
    "75": "Summoner's Rift - 6v6 Hexakill",
    "76": "Summoner's Rift - Ultra Rapid Fire",
    "78": "Howling Abyss - One For All: Mirror Mode",
    "83": "Summoner's Rift - Co-op vs AI Ultra Rapid Fire",
    "98": "Twisted Treeline - 6v6 Hexakill",
    "100": "Butcher's Bridge - 5v5 ARAM",
    "317": "Crystal Scar - Definitely Not Dominion",
    "325": "Summoner's Rift - All Random",
    "400": "Summoner's Rift - 5v5 Draft Pick",
    "420": "Summoner's Rift - 5v5 Ranked Solo",
    "430": "Summoner's Rift - 5v5 Blind Pick",
    "440": "Summoner's Rift - 5v5 Ranked Flex",
    "450": "Howling Abyss - 5v5 ARAM",
    "460": "Twisted Treeline - 3v3 Blind Pick",
    "470": "Twisted Treeline - 3v3 Ranked Flex",
    "600": "Summoner's Rift - Blood Hunt Assassin",
    "610": "Cosmic Ruins Dark Star: Singularity",
    "700": "Summoner's Rift - Clash",
    "800": "Twisted Treeline - Co-op vs. AI Intermediate Bot",
    "810": "Twisted Treeline - Co-op vs. AI Intro Bot",
    "820": "Twisted Treeline - Co-op vs. AI Beginner Bot",
    "830": "Summoner's Rift - Co-op vs. AI Intro Bot",
    "840": "Summoner's Rift - Co-op vs. AI Beginner Bot",
    "850": "Summoner's Rift - Co-op vs. AI Intermediate Bot",
    "900": "Summoner's Rift - ARURF",
    "910": "Crystal Scar - Ascension",
    "920": "Howling Abyss - Legend of the Poro King",
    "940": "Summoner's Rift - Nexus Siege",
    "950": "Summoner's Rift - Doom Bots Voting",
    "960": "Summoner's Rift - Doom Bots Standard",
    "980": "Valoran City Park - Star Guardian Invasion: Normal",
    "990": "Valoran City Park - Star Guardian Invasion: Onslaught",
    "1000": "Overcharge - PROJECT: Hunters",
    "1010": "Summoner's Rift - Snow ARURF",
    "1020": "Summoner's Rift - One for All",
    "1030": "Crash Site - Odyssey Extraction: Intro",
    "1040": "Crash Site - Odyssey Extraction: Cadet",
    "1050": "Crash Site - Odyssey Extraction: Crewmember",
    "1060": "Crash Site - Odyssey Extraction: Captain",
    "1070": "Crash Site - Odyssey Extraction: Onslaught",
    "1090": "Convergence - Teamfight Tactics",
    "1100": "Convergence - Ranked Teamfight Tactics",
}

MATCH_MODE_TYPE = {
    "CLASSIC": "Classic Summoner's Rift and Twisted Treeline",
    "ODIN": "Dominion/Crystal Scar",
    "ARAM": "ARAM",
    "TUTORIAL": "Tutorial",
    "URF": "URF",
    "DOOMBOTSTEEMO": "Doom Bot",
    "ONEFORALL": "One for All",
    "ASCENSION": "Ascension",
    "FIRSTBLOOD": "Snowdown Showdown",
    "KINGPORO": "Legend of the Poro King",
    "SIEGE": "Nexus Siege",
    "ASSASSINATE": "Blood Hunt Assassin",
    "ARSR": "All Random Summoner's Rift",
    "DARKSTAR": "Dark Star: Singularity",
    "STARGUARDIAN": "Star Guardian Invasion",
    "PROJECT": "PROJECT: Hunters",
    "GAMEMODEX": "Nexus Blitz",
    "ODYSSEY": "Odyssey: Extraction",
}